
DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NUMEROMATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);



DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DOMICLIO VARCHAR(100) NOT NULL, DNI INT NOT NULL, FECHAINGRESO DATE NOT NULL);


INSERT INTO ODONTOLOGOS (NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES (111, 'Natalia', 'Kohen'), (222, 'Claudio', 'Caicedo');


INSERT INTO PACIENTES (NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA) VALUES ('Emiliano', 'Cellilli', 'Calle Calle-calle 2323', 123456, '2023-05-24')
